petrol_server/app/petrol/urls.py
from petrol_server.app.petrol import views
from django.conf.urls import patterns, url
from django.contrib.auth.views import login


urlpatterns = patterns('',
    url(r'^$', views.main),
    url(r'^balance/(?P<company_id>\d+)/$', views.balance),
    url(r'^statistic', views.statistic),

    (r'^accounts/login/$',  login),
    (r'^accounts/logout/$', views.logout_view),
    (r'^logout/$', views.logout_view),


)

petrol_server/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('petrol_server.app.petrol.urls')),
)

petrol_server/app/petrol/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth import models as auth_models


class User(models.Model):
    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    user = models.OneToOneField(auth_models.User)
    sms_telephone = models.CharField(max_length=13, blank=True)
    fax_telephone = models.CharField(max_length=13, blank=True)

    def __unicode__(self):
        return unicode(self.user)


class Company(models.Model):
    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    title = models.CharField(max_length=100, verbose_name='Название')
    user = models.ForeignKey(User, verbose_name='Пользователь')

    def __unicode__(self):
        return unicode(self.title)


class Card(models.Model):
    class Meta:
        verbose_name = 'Карта'
        verbose_name_plural = 'Карты'

    number = models.CharField(max_length=15, verbose_name='Номер карты')

    def __unicode__(self):
        return unicode(self.number)


class PetrolStation(models.Model):
    class Meta:
        verbose_name = 'АЗС'
        verbose_name_plural = 'АЗС'
    address = models.CharField(max_length=200, verbose_name='Адрес')

    def __unicode__(self):
        return unicode(self.address)


class Cardholder(models.Model):
    class Meta:
        verbose_name = 'Держатель'
        verbose_name_plural = 'Держатели'

    card = models.ForeignKey(Card, verbose_name='Карта')
    company = models.ForeignKey(Company, verbose_name='Компания')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')

    def __unicode__(self):
        return u'%s - %s' % (self.card, self.company)


class CardTransaction(models.Model):
    class Meta:
        verbose_name = 'Транзакция'
        verbose_name_plural = 'Транзакции'

    made_at = models.DateField(verbose_name='Дата')

    card = models.ForeignKey(Card, verbose_name='Карта')

    card_holder = models.ForeignKey(Cardholder, verbose_name='Держатель')
    petrol_station = models.ForeignKey(PetrolStation, verbose_name='АЗС')

    fuel = models.CharField(max_length=300, verbose_name='Вид топлива')
    volume = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Количество')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')

    is_approved = models.BooleanField(default=False, verbose_name='Проведен')
    is_no_need_attention = models.BooleanField(default=True, verbose_name='Правильная транзакция')


class Payment(models.Model):
    class Meta:
        verbose_name = 'Платежи'
        verbose_name_plural = 'Платежи'

    company = models.ForeignKey(Company)
    amount = models.DecimalField(max_digits=20, decimal_places=2, verbose_name='Сумма')
    date = models.DateTimeField(editable=True, verbose_name='Дата')

    def __unicode__(self):
        return u'%s - %s' % (self.amount, self.company)


class Discount(models.Model):
    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'

    company = models.ForeignKey(Company)
    discount = models.DecimalField(max_digits=4, decimal_places=2, verbose_name='Скидка')
    date_from = models.DateField(verbose_name='Начальная дата')
    date_to = models.DateField(verbose_name='Конечная дата')

    def __unicode__(self):
        return u'%s - %s (%s - %s)' % (self.company, self.discount, self.date_from, self.date_to)

petrol_server/app/petrol/forms.py
from django import forms
from petrol_server.app.petrol import models

import datetime


class PeriodForm(forms.Form):
    start_period = forms.DateField(input_formats=['%d.%m.%Y'],
                                   initial=(datetime.datetime.today()
                                 - datetime.timedelta(30/1)).strftime("%d.%m.%Y")
                                 )

    end_period = forms.DateField(input_formats=['%d.%m.%Y'],
                                 initial=datetime.datetime.today().strftime("%d.%m.%Y"))


class DiscountForm(forms.Form):

    class Meta:
        model = models.Discount

petrol_server/app/petrol/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Sum
from django.shortcuts import render_to_response
from petrol_server.app.petrol import models
from petrol_server.app.petrol import forms
from petrol_server.app.petrol import utils
from datetime import datetime


@login_required(login_url='accounts/login/')
@user_passes_test(lambda user: not user.is_staff, login_url='/admin/')
def main(request):
    try:
        company = models.Company.objects.get(user__user=request.user.id)
    except ObjectDoesNotExist as e:
        return render_to_response('errors.html', {'error': e})

    form = forms.PeriodForm(request.GET)
    balance = utils.get_balance(company, on_date=datetime.now())
    context = {
        'form': forms.PeriodForm,
        'company': company,
        'balance': balance,
        }
    if form.is_valid():
        start_period = datetime.strptime(form['start_period'].value(), '%d.%m.%Y')
        end_period = datetime.strptime(form['end_period'].value(), '%d.%m.%Y')
        transactions = utils.build_discount_transactions(company, start_period, end_period)
        context = {
                'summary_data': utils.get_summary_data(transactions),
                'card_transactions': utils.get_card_transactions(transactions),
                'form': form,
                'company': company,
                'balance': balance,
                }

    return render_to_response('card_transactions.html', context)

@login_required(login_url='accounts/login/')
@user_passes_test(lambda user: user.is_staff, login_url='/admin/')
def statistic(request):
    form = forms.PeriodForm(request.GET)

    if not form.is_valid():
        return render_to_response('statistic.html', {'form': form})

    start_period = datetime.strptime(form['start_period'].value(), '%d.%m.%Y')
    end_period = datetime.strptime(form['end_period'].value(), '%d.%m.%Y')

    companies_data = models.CardTransaction.objects.filter(
        made_at__range=[start_period, end_period],
    ).values_list(
        'card_holder__company__title',
    ).annotate(
        amount=Sum('price', field='volume * price'),
        volume=Sum('volume'),
    )

    companies_data = [(utils.get_balance(models.Company.objects.get(title=company_data[0]), start_period), utils.get_balance(models.Company.objects.get(title=company_data[0]), end_period),) + company_data for company_data in companies_data]

    context = {
        'form': form,
        'companies_data': companies_data,
    }

    return render_to_response('statistic.html', context)


@login_required(login_url='accounts/login/')
@user_passes_test(lambda user: not user.is_staff, login_url='/admin/')
def balance(request, company_id):
    try:
        company = models.Company.objects.get(user__user__id=request.user.id)
    except ObjectDoesNotExist as e:
        return render_to_response('errors.html', {'error': e})

    payments = models.Payment.objects.filter(
        company_id=company_id
    ).order_by('date')
    for payment in payments:
        payment.balance = utils.get_balance(company, payment.date)

    context = {'payments': payments}

    return render_to_response('payments.html', context)


def logout_view(request):
    logout(request)
    return render_to_response('success_logout.html')

templates/base.html
<html>
<head lang="en">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

    <link href="/static/css/bootstrap.css" rel="stylesheet" media="screen">
    <script src="/static/js/bootstrap.js"></script>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <script type="text/javascript">
        $(function() {
            $.datepicker.setDefaults( {dateFormat: "dd.mm.yy"} );
            $( "#id_start_period" ).datepicker();
            $( "#id_end_period" ).datepicker();
        });
    </script>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

</body>
</html>

templates/card_transactions.html
{% extends 'base.html' %}

{% block title %}PetrolServer{% endblock %}

{% load summary_extras %}

{% block content %}
    <div class="row" xmlns="http://www.w3.org/1999/html">
        <div class="col-md-8">
            <p>Кабинет компании {{ company.title }}</p>
            <span>Ваш баланс: <a href="/balance/{{ company.id }}">{{ balance|floatformat:2 }}</a></span>
        </div>
        <div class="col-md-4">
            <div id="brent" style="background: #333333; width:186px; height:61px; border: 1x solid #ccc; color:#84057A; text-decoration:none; text-align:left; top; overflow: hidden; font-style:normal; font-variant:normal; font-weight:normal; font-size:9px; font-family:Verdana, sans-serif;">
                <a href="http://www.forexpf.ru/" title="Цены на нефть" target="_blank" style="line-height:14px;color: #FF6600;text-decoration:none;padding-left: 50px;">Цена на нефть</a>
                <br>
                <a href="http://www.forexpf.ru/chart/brent/" title="Brent" target="_blank" style="line-height:15px;color: #CCCCCC;text-decoration:none;padding-left: 33px;">Brent</a>
                <a href="http://www.forexpf.ru/chart/lightsweet/" title="Light Sweet" target="_blank" style="line-height:15px;color:#ccc;text-decoration:none;padding-left: 63px;">Light</a>
            </div>
        </div>
        <script src="http://www.forexpf.ru/_informer_/brent_.php"></script>
    </div>

    <p> Выбрать период: </p>
    <form action="" method="GET">
        с:{{ form.start_period }}
        до:{{ form.end_period }}
        <input type="submit" value="Показать">
    </form>

    {% include 'summary_data.html' %}

    <table class="table">
        {% for card_transaction in card_transactions %}
        <tbody>
            <tr>
                <th>Карта {{ card_transaction.0 }}</th>
            </tr>
            <tr>
                <th>Дата</th>
                <th>Адрес АЗС</th>
                <th>Услуга</th>
                <th>Количество</th>
                <th>Цена со скидкой</th>
                <th>Стоимость на ТО</th>
                <th>Скидка</th>
                <th>Стоимость со скидкой</th>
            </tr>

            {% for transaction in card_transaction.1 %}
            <tr>
                <td>{{ transaction.made_at|date:"d.m.Y" }}</td>
                <td>{{ transaction.petrol_station }}</td>
                <td>{{ transaction.fuel }}</td>
                <td>{{ transaction.volume }}</td>
                <td>{{ transaction.price|minus:transaction.discount|floatformat:2 }}</td>
                <td>{{ transaction.amount|floatformat:2 }}</td>
                <td>{{ transaction.volume|multipl:transaction.discount|floatformat:2 }}</td>
                <td>{{ transaction.price|minus:transaction.discount|multipl:transaction.volume|floatformat:2 }}</td>
            </tr>
            {% endfor %}
            <tr>
                <th>Итого:</th>
                <th></th>
                <th></th>
                <th>{{ card_transaction.2|floatformat:2 }}</th>
                <th></th>
                <th>{{ card_transaction.3|floatformat:2 }}</th>
                <th>{{ card_transaction.4|floatformat:2 }}</th>
                <th>{{ card_transaction.5|floatformat:2 }}</th>
            </tr>

        </tbody>
        {% endfor %}
    </table>

    <form method="GET" action="/logout/">
        <input class="btn btn-default" type="submit" value="Выход">
    </form>
{% endblock %}

templates/errors.html
{% extends 'base.html' %}

{% block title %}PetrolServer{% endblock %}
{% block content %}
    {% if error %}
        {% for e in error %}
            <p> Ошибка: {{ e }} </p>
        {% endfor %}
    {% endif %}
    <form method="GET" action="/logout/">
        <input class="btn btn-default" type="submit" value="Выход">
    </form>
{% endblock %}

templates/payments.html
{% extends 'base.html' %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th> Дата </th>
                <th> Сумма пополнения </th>
                <th> Баланс после пополнения </th>
            </tr>
        </thead>
        <tbody>
            {% for row in payments %}
                <tr>
                    <td>{{ row.date|date:"d.m.Y" }}</td>
                    <td>{{ row.amount }}</td>
                    <td>{{ row.balance|floatformat:2 }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <form method="GET" action="/">
        <input class="btn btn-info" type="submit" value="Назад">
    </form>

{% endblock %}

templates/statistic.html
{% extends 'base.html' %}

{% block content %}
    <p> Введите период:</p>
    <form action="" method="GET">
        с:{{ form.start_period }}
        до:{{ form.end_period }}
        <input type="submit" value="Показать">
    </form>

    <table class="table">
        <tbody>
        <tr>
            <th>Компания</th>
            <th>Реализация (л.)</th>
            <th>Реализация (грн.)</th>
            <th>Баланс на начало периода (грн.)</th>
            <th>Баланс на конец периода (грн.)</th>
        </tr>
    {% for company_data in companies_data %}
        <tr>
            <td>{{ company_data.2 }}</td>
            <td>{{ company_data.3|floatformat:2 }}</td>
            <td>{{ company_data.4|floatformat:2 }}</td>
            <td>{{ company_data.0|floatformat:2 }}</td>
            <td>{{ company_data.1|floatformat:2 }}</td>
        </tr>
    {% endfor %}
        </tbody>
    </table>

    <form method="GET" action="/">
        <input class="btn btn-info" type="submit" value="Назад">
    </form>

{% endblock %}

templates/success_logout.html
{% extends 'base.html' %}

{% block title %}  Succsess logout {% endblock %}

{% block content %}
    <div>
        <p>Вы успешно вышли, но вы всегда можете <a href="/">войти</a></p>
    </div>
{% endblock %}

templates/summary_data.html
{% load summary_extras %}

{% for element in summary_data %}
    {% if element == 'fuel' %}
        {% with summary_data|value_by_key:element as fuels %}
            {% for fuel in fuels %}
                {% with fuels|value_by_key:fuel as volume %}
                    <span><strong>{{ fuel }}</strong> - {{ volume }} л.</span><br>
                {% endwith %}
            {% endfor %}
        {% endwith %}
    {% endif %}

    {% if element == 'total' %}
        {% with summary_data|value_by_key:element as total %}
            <span><strong>Реализация</strong> - {{ total|floatformat:2 }} грн.</span><br>
        {% endwith %}
    {% endif %}

    {% if element == 'saved_money' %}
        {% with summary_data|value_by_key:element as saved_money %}
            <span><strong>Скидка</strong> - {{ saved_money|floatformat:2 }} грн.</span><br>
        {% endwith %}
    {% endif %}
{% endfor %}